//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnookerApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Friends
    {
        public int playerId { get; set; }
        public string friendFirstName { get; set; }
        public string friendLastName { get; set; }
        public string friendNick { get; set; }
    }
}
