//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnookerApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameStatistics
    {
        public int gameId { get; set; }
        public string player1 { get; set; }
        public string player2 { get; set; }
        public Nullable<int> BestOf { get; set; }
        public int scorePlayer1 { get; set; }
        public int scorePlayer2 { get; set; }
        public int topBreakPlayer1 { get; set; }
        public int topBreakPlayer2 { get; set; }
        public string winningPlayer { get; set; }
        public int gameNumber { get; set; }
        public System.DateTime gameDate { get; set; }
    }
}
