//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnookerApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class History
    {
        public int gameID { get; set; }
        public Nullable<int> vsPlayer { get; set; }
        public Nullable<int> round { get; set; }
        public int playerId { get; set; }
        public System.DateTime gameDate { get; set; }
    }
}
