//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnookerApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerProfile
    {
        public int isHidden { get; set; }
        public int isPublic { get; set; }
        public int friendsOnly { get; set; }
        public int active { get; set; }
    }
}
