//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnookerApiProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnookerApiProject2_dbEntities : DbContext
    {
        public SnookerApiProject2_dbEntities()
            : base("name=SnookerApiProject2_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<Statistics> Statistics { get; set; }
        public virtual DbSet<TopTenBreaks> TopTenBreaks { get; set; }
        public virtual DbSet<UserProfile> UserProfile { get; set; }
        public virtual DbSet<GameStatistics> GameStatistics { get; set; }
        public virtual DbSet<RegisteredPlayers> RegisteredPlayers { get; set; }
    }
}
