//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnookerApiProject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SnookerAppEntitie3 : DbContext
    {
        public SnookerAppEntitie3()
            : base("name=SnookerAppEntitie3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Players> Players { get; set; }
        public virtual DbSet<Friends> Friends { get; set; }
        public virtual DbSet<History> History { get; set; }
        public virtual DbSet<PlayerProfile> PlayerProfile { get; set; }
        public virtual DbSet<Statistics> Statistics { get; set; }
        public virtual DbSet<TopTenBreaks> TopTenBreaks { get; set; }
    }
}
