//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnookerApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Statistics
    {
        public Nullable<int> successPots { get; set; }
        public Nullable<int> successLong { get; set; }
        public Nullable<int> successRest { get; set; }
        public Nullable<int> failedPots { get; set; }
        public Nullable<int> failedLong { get; set; }
        public Nullable<int> failedRest { get; set; }
        public System.DateTime gameDate { get; set; }
        public int playerId { get; set; }
    }
}
