//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SnookerApiProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TopTenBreaks
    {
        public System.DateTime breakDate { get; set; }
        public int playerId { get; set; }
        public Nullable<int> topOne { get; set; }
        public Nullable<int> topTwo { get; set; }
        public Nullable<int> topThree { get; set; }
        public Nullable<int> topFour { get; set; }
        public Nullable<int> topFive { get; set; }
        public Nullable<int> topSix { get; set; }
        public Nullable<int> topSeven { get; set; }
        public Nullable<int> topEight { get; set; }
        public Nullable<int> topNine { get; set; }
        public Nullable<int> topTen { get; set; }
    }
}
